[package]
name = "conway"
version = "0.2.1"
edition = "2024"

[dependencies]
ahash = "0.8.12"
clap = { version = "4.5.39", features = ["derive"] }
crossterm = "0.29.0"
ctrlc =  { version = "3.4.7", features = ["termination"] }
fastrand = "2.3.0"
